# Generated by Django 3.1.4 on 2020-12-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('O', 'Official'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('C', 'Casual'), ('I', 'Indoors')], max_length=2),
        ),
    ]
