# Generated by Django 3.1.4 on 2020-12-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201221_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentaddress',
            old_name='countries',
            new_name='country',
        ),
    ]
